spring:
  application:
    name: ticketria-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:

        - id: ticketria-user-service
          uri: lb://ticketria-user-service
          predicates:
            - Path=/api/v1/users/**

        - id: ticketria-service
          uri: lb://ticketria-service
          predicates:
            - Path=/api/v1/trips/**

        - id: ticketria-email-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/emails/**
        - id: ticketria-auth-service
          uri: http://localhost:9191
          predicates:
            - Path=/api/v1/auth/**
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 9090

